# Generated by Django 3.0.7 on 2021-03-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patientmodel',
            fields=[
                ('patId', models.IntegerField(primary_key=True, serialize=False)),
                ('patName', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
